#!/bin/bash
source ../setup-env

CLASSPATH=$SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar:$KAFKA_HOME/libs/log4j-1.2.15.jar

IN_EVENT_FILE=simulator_data_incident_shortened.csv
#IN_EVENT_FILE=in-events-rush-20min.log

java -cp $CLASSPATH org.speedd.util.EventPlayer -c ../producer-docker.properties -t speedd-traffic-in-events -p org.speedd.traffic.TrafficAimsunReadingCsv2Event $IN_EVENT_FILE

