#!/bin/bash
source ../setup-env-mesos

CLASSPATH=$SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar:$KAFKA_HOME/libs/log4j-1.2.15.jar

IN_EVENT_FILE=dataRushHourTruncated.csv

$JAVA_CMD -cp $CLASSPATH org.speedd.util.EventPlayer -c ../producer-mesos.properties -t speedd-traffic-in-events -p org.speedd.traffic.TrafficAggregatedReadingCsv2Event $IN_EVENT_FILE

