#!/bin/bash
source ../setup-env

MODE=remote

$STORM_CMD jar $SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.speedd.SpeeddTopology \
-D nimbus.host=nimbus -D nimbus.thrift.port=6627 \
-m remote \
-Dproducer.type=sync -Dcompression.codec=none -Dserializer.class=org.speedd.kafka.JsonEventEncoder \
-Dmetadata.broker.list=kafka:9092 \
-Dzookeeper.connect=zk:2181 \
-Dzookeeper.connection.timeout.ms=1000000 \
-Dtopic.in.events=speedd-traffic-in-events \
-Dtopic.out.events=speedd-traffic-out-events \
-Dtopic.actions=speedd-traffic-actions \
-Dtopic.actions.confirmed=speedd-traffic-actions-confirmed \
-Dtopic.admin=speedd-traffic-admin \
-Dproton.epnPath=CNRSIntegration.json \
-Dspeedd.inEventScheme=org.speedd.traffic.TrafficAimsunReadingScheme \
-Dspeedd.dmClass=org.speedd.dm.TrafficDecisionMakerBolt \
-Dspeedd.enricherPath=rochade_sensor_and_aimsun_labels_partitions.csv \
-Dspeedd.enricherClass=org.speedd.traffic.TrafficEnricherBolt \
&
