#!/bin/bash
source ../setup-env

CLASSPATH=$SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar:$KAFKA_HOME/libs/log4j-1.2.15.jar

IN_EVENT_FILE=FeedzaiIntegrationData.csv

$JAVA_CMD -cp $CLASSPATH org.speedd.util.EventPlayer -c ../producer.properties -t speedd-in-events -p org.speedd.fraud.FraudAggregatedReadingCsv2Event $IN_EVENT_FILE

