#!/bin/bash
source ../setup-env

MODE=remote

$STORM_CMD jar $SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.speedd.SpeeddTopology \
-D nimbus.host=nimbus -D nimbus.thrift.port=6627 \
-m remote \
-Dproducer.type=sync -Dcompression.codec=none -Dserializer.class=org.speedd.kafka.JsonEventEncoder \
-Dmetadata.broker.list=kafka:9092 \
-Dzookeeper.connect=zk:2181 \
-Dzookeeper.connection.timeout.ms=1000000 \
-Dtopic.in.events=speedd-fraud-in-events \
-Dtopic.out.events=speedd-fraud-out-events \
-Dtopic.actions=speedd-fraud-actions \
-Dtopic.actions.confirmed=speedd-fraud-actions-confirmed \
-Dtopic.admin=speedd-fraud-admin \
-Dproton.epnPath=FeedzaiFraudIntegration.json \
-Dspeedd.inEventScheme=org.speedd.fraud.FraudAggregatedReadingScheme \
-Dspeedd.dmClass=org.speedd.dm.EchoBolt \
-Dspeedd.enricherPath= \
-Dspeedd.enricherClass=org.speedd.fraud.FraudEnrichmentBolt \
&
