#!/bin/bash
source ../setup-env

if [ -z $1 ]
then
	echo "USAGE: $0 <number of reps>"
	exit 1
fi

CLASSPATH=$SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar:$KAFKA_HOME/libs/log4j-1.2.15.jar

IN_EVENT_FILE=generated-events.csv

java -cp $CLASSPATH org.speedd.util.EventPlayer -c ../producer-docker.properties -t speedd-fraud-in-events -p org.speedd.fraud.FraudAggregatedReadingCsv2Event -s -r $1 $IN_EVENT_FILE

