#!/bin/bash
source ./setup-env-mesos

$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-traffic-in-events --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-traffic-out-events --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-traffic-actions --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-traffic-admin --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-fraud-in-events --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-fraud-out-events --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-fraud-actions --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-fraud-admin --replication-factor 1 --partitions 1 --zookeeper localhost:2181
