#!/bin/bash
KAFKA_HOME=/opt/kafka_2.8.0-0.8.1.1

$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-in-events --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-out-events --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-actions --replication-factor 1 --partitions 1 --zookeeper localhost:2181
$KAFKA_HOME/bin/kafka-topics.sh --create --topic speedd-admin --replication-factor 1 --partitions 1 --zookeeper localhost:2181
