#!/bin/bash
STORM_HOME=/opt/apache-storm-0.9.4

KAFKA_HOME=/opt/kafka_2.10-0.8.22.1

SPEEDD_HOME=~/speedd

SPEEDD_RUNTIME_HOME=$SPEEDD_HOME/speedd-runtime

SPEEDD_RUNTIME_LIB=$SPEEDD_RUNTIME_HOME/target

JAVA_CMD=$JAVA_HOME/bin/java

CLASSPATH=$SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar:$KAFKA_HOME/libs/log4j-1.2.15.jar

$JAVA_CMD -cp $CLASSPATH org.speedd.util.EventPlayer $*

