#!/bin/bash

if [ -z ${SPEEDD_HOME+x} ]; 
then 
	SPEEDD_HOME=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../.." && pwd );
	echo "SPEEDD_HOME is unset, setting to $SPEEDD_HOME";
else 
	echo "SPEEDD_HOME is set to $SPEEDD_HOME"; 
fi

if [ -z ${STORM_HOME+x} ]; 
then 
	STORM_HOME=/opt/apache-storm-0.9.2-incubating
	echo "STORM_HOME is unset, setting to $STORM_HOME";
else 
	echo "STORM_HOME is set to $STORM_HOME"; 
fi

if [ -z ${KAFKA_HOME+x} ]; 
then 
	KAFKA_HOME=/opt/kafka_2.8.0-0.8.1.1
	echo "KAFKA_HOME is unset, setting to $KAFKA_HOME";
else 
	echo "KAFKA_HOME is set to $KAFKA_HOME"; 
fi

SPEEDD_RUNTIME_HOME=$SPEEDD_HOME/speedd-runtime

STORM_CMD=$STORM_HOME/bin/storm

SPEEDD_RUNTIME_LIB=$SPEEDD_RUNTIME_HOME/target

JAVA_CMD=$JAVA_HOME/bin/java
