#!/bin/bash
STORM_HOME=/opt/apache-storm-0.9.2-incubating
SPEEDD_HOME=~/speedd
SPEED_RUNTIME_HOME=$SPEEDD_HOME/speedd-runtime
STORM_CMD=$STORM_HOME/bin/storm
SPEEDD_RUNTIME_LIB=$SPEED_RUNTIME_HOME/target
PROPS=speedd.properties
MODE=remote
#sudo /opt/apache-storm-0.9.2-incubating/bin/storm jar ~/speedd/speedd-runtime/target/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.speedd.SpeeddTopology speedd.properties remote


$STORM_CMD jar $SPEEDD_RUNTIME_LIB/speedd-runtime-0.0.1-SNAPSHOT-jar-with-dependencies.jar org.speedd.SpeeddTopology $PROPS $MODE &

